<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>OnePatch.Client</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DeviceId" Version="6.9.0" />
    <PackageReference Include="DeviceId.Linux" Version="6.9.0" />
    <PackageReference Include="DeviceId.Windows" Version="6.9.0" />
    <PackageReference Include="DeviceId.Windows.Wmi" Version="6.9.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.0" />
    <PackageReference Include="System.Management" Version="9.0.3" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.7" />
  </ItemGroup>
</Project>
